### PR TITLE
Refactor to use showQuickPick to reduce test surface

### PR DESCRIPTION
**Pull request by michael-weng**
The onButtonPressed param was never utilized, so opt to use the simpler showQuickPick instead to keep things simple.

Issue: #1023

### CODE REVIEW

**Comment by award999** [comment]
@swift-server-bot add to whitelist

**Comment by award999** [comment]
@swift-server-bot test this please

**Comment by award999** [comment]
@swift-server-bot test this please

**Review by award999 — APPROVED** [review]

**Comment by michael-weng** [comment]
Merged with 
https://github.com/swiftlang/vscode-swift/pull/1063

**Pull request closed without merging**
