### PR TITLE
Ignore unnecessary files when packaging extension

### PR DESCRIPTION
**Pull request by plemarquand**
Slim down the extension by ignoring files that don't need to be included in the .vsix

Issue: #1078

### CODE REVIEW

**Comment by adam-fowler** [comment]
Not sure about the CHANGELOG. Don't know where VSCode gets that from

**Review by award999 — CHANGES_REQUESTED** [review]
So we don't have to update this every time, if you checkout https://code.visualstudio.com/api/working-with-extensions/publishing-extension#using-.vscodeignore, you can ! to include something so what I've seen work well before is ignore everything (**/*) by default and use ! to explicitly only include what we want

**Comment by plemarquand** [comment]
@adam-fowler I think you're right, the tooltip on the Changelog tab in the extension's marketplace page implies it comes from the CHANGELOG.md. I've included that.

@award999 I've moved over to the recommended explicit include approach.

**Review by award999 — APPROVED** [review]
LGTM

**Comment by adam-fowler** [comment]
Don't know enough about the `.vscodeignore` but what does `**/*` do? But otherwise looks good

**Comment by award999** [comment]
> Don't know enough about the `.vscodeignore` but what does `**/*` do? But otherwise looks good

Basically this approach removes everything by default, and then preceding each item with ! will add those items in. That way we don't have to add new entries to this file every time we add a root level item. The developer has to explicitly add a new ! exception for it to end up in the vsix bundle

**Review by adam-fowler — APPROVED** [review]

**Pull request merged**
