### PR TITLE
Add CODEOWNERS file

### PR DESCRIPTION
**Pull request by adam-fowler**

### CODE REVIEW

**Review by 0xTim — APPROVED** [review]
LGTM - but there's an error because I don't have write access to the repo

Screenshot 2024-06-16 at 19 03 37

**Comment by adam-fowler** [comment]
Ok I'll add you.

**Comment by adam-fowler** [comment]
> LGTM - but there's an error because I don't have write access to the repo
> 
done

**Comment by 0xTim** [comment]
All green

**Review by award999 — APPROVED** [review]
LGTM

**Pull request merged**
