### PR TITLE
Use @vscode/test-cli to run tests

### PR DESCRIPTION
**Pull request by plemarquand**
Migrates to the new [@vscode/test-cli](https://github.com/microsoft/vscode-test-cli) package to download the appropriate VS Code and run the tests. This streamlines the test setup code, and should be a more reliable way to run the tests as VS Code evolves.

Hopefully this also helps with the occasional SIGSEGV errors that happen in CI on startup.

### CODE REVIEW

**Comment by award999** [comment]
I have this setup with my WIP for unit testing, I'll push that and we can reconcile this patch with that

**Comment by plemarquand** [comment]
@award999 ah, sorry I didn't realize you already had some code going for this. I wrote most of this a while ago and revived it after seeing @matthewbastien getting those SIGSEGV errors in CI hoping this would help.

**Comment by award999** [comment]
> @award999 ah, sorry I didn't realize you already had some code going for this. I wrote most of this a while ago and revived it after seeing @matthewbastien getting those SIGSEGV errors in CI hoping this would help.

NP, that patch will take longer to get in so let's use this one for just the test runner portion

**Review by award999 — APPROVED** [review]

**Comment by plemarquand** [comment]
@swift-server-bot test this please

**Comment by plemarquand** [comment]
@swift-server-bot test this please

**Comment by plemarquand** [comment]
Thanks @award999 for providing the code you’d written for this PR

**Comment by plemarquand** [comment]
@swift-server-bot test this please

**Comment by plemarquand** [comment]
@swift-server-bot test this please

**Comment by plemarquand** [comment]
@swift-server-bot test this please

**Comment by plemarquand** [comment]
@swift-server-bot test this please

**Review by adam-fowler — APPROVED** [review]
Looks good

**Pull request merged**
