### PR TITLE
[CI] GitHub Actions support

### PR DESCRIPTION
**Pull request by shahmishal**

### CODE REVIEW

**Comment by shahmishal** [comment]
https://github.com/swiftlang/vscode-swift/issues/1161
https://github.com/swiftlang/vscode-swift/issues/1162

**Comment by award999** [comment]
Thanks so much @shahmishal. Looking at the output test fail but  step succeeds. If the script provided to `linux_build_command: ./docker/test.sh` returns a non-zero exit code, is it expected to fail? If so I'll run down why the exit code is wrong

**Comment by plemarquand** [comment]
@shahmishal Do you have any guidance on how to run a GH action at desk? Ideally the tests for just one Swift version.

**Comment by shahmishal** [comment]
> @shahmishal Do you have any guidance on how to run a GH action at desk? Ideally the tests for just one Swift version.

To reproduce the steps locally: https://github.com/swiftlang/github-workflows?tab=readme-ov-file#running-workflows-locally

**Comment by plemarquand** [comment]
Thanks, I was able to test a single swift configuration locally with act using the matrix flag: `act -j tests --matrix swift_version:5.8`

**Comment by plemarquand** [comment]
@swift-ci test this Linux nightly-main

**Comment by plemarquand** [comment]
@swift-ci test Linux nightly-main

**Comment by plemarquand** [comment]
@swift-ci test this Linux

**Comment by plemarquand** [comment]
@swift-ci please test this

**Comment by plemarquand** [comment]
@swift-ci please test this

**Review by award999 — APPROVED** [review]

**Pull request merged**
