### PR TITLE
Improve LSP configuration change notification

### LINKED ISSUE #747: When disabling sourcekit-lsp in settings, the popup implies the server will be restarted
The popup window [defined here](https://github.com/swift-server/vscode-swift/blob/f3b76be242feda0763170aa14ff555386b607527/src/sourcekit-lsp/LanguageClientManager.ts#L161-L174) says "Changing LSP settings requires the language server be restarted." but of course if the setting changed was to disable sourcekit-lsp, the server doesn't actually get restarted.

**Describe the solution you'd like**
This setting should probably be special cased with a message like "Sourcekit-lsp disabled. Click OK to shut down language server." or the like.

### PR DESCRIPTION
**Pull request by matthewbastien**
Issue: #747 

Adds extra checks surrounding enablement of SourceKit-LSP to improve the wording of the configuration changed notification.

### CODE REVIEW

**Review by award999 — APPROVED** [review]
lgtm

**Comment by award999** [comment]
@swift-server-bot test this please

**Review by adam-fowler — APPROVED** [review]
Looks good

**Comment by matthewbastien** [comment]
@swift-server-bot test this please

**Pull request merged**
